version: '3'
services:
  mysql:
    image: "mysql/mysql-server:latest"
    command: '--default-authentication-plugin=mysql_native_password'
    expose:
      - "3306"
    ports:
    - "3306:3306"
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_ROOT_HOST: "%"
